name: Release

on:
  repository_dispatch:
    types: [swiftlint-release]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update binary package
        run: >
          sed -i
          -e "s#/[0-9]\{1,\}\.[0-9]\{1,\}\.[0-9]\{1,\}/#/${{ github.event.client_payload.tag }}/#"
          -e "s/[a-fA-F0-9]\{64\}/${{ github.event.client_payload.checksum }}/"
          Package.swift
      - name: Configure Git author
        id: configure_git_author
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ github.repository_owner }}
      - name: Configure author
        run: |
          git config --local user.name "${{ steps.configure_git_author.outputs.name }}"
          git config --local user.email "${{ steps.configure_git_author.outputs.email }}"
      - name: Commit
        run: |
          git add Package.swift
          git commit -m "Release ${{ github.event.client_payload.tag }}"
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.client_payload.title }}
          tag: ${{ github.event.client_payload.tag }}
          body: >
            Check out the changes made in the
            [SwiftLint release](https://github.com/realm/SwiftLint/releases/tag/${{ github.event.client_payload.tag }})
            associated with this version.
          draft: false
